### create visitors

POST http://localhost:3000/appointment
Content-Type: application/json

{
  "newname": "Wan Zuhaida",
  "newcompany": "Megah Holding",
  "newpurpose": "Meeting",
  "newphoneNumber": "01111111111",
  "newdate": "2023-7-1",
  "newtime": "09:00 AM",
  "newuser": {
    "name": "Ahmad",
    "email": "ahmad33@company.com",
    "role": "supervisor"
  }
}