### create visitors

POST http://localhost:3000/appointment
Content-Type: application/json

{
  "newname": "Alyaa Zafira",
  "newcompany": "-",
  "newpurpose": "Interview",
  "newphoneNumber": "0112233445",
  "newdate": "2023-7-1",
  "newtime": "09:00 AM",
  "newuser": {
    "name": "Ahmad",
    "email": "ahmad33@company.com",
    "role": "supervisor"
  }
}